_target_: glood.src.datasets.sharded_dataset.ShardedDatasetSeries
shard_dir:
  _target_: glood.src.utils.env.attach_to_cwd
  path: ${hyperparams_dataset.shard_dir}
shuffle: ${hyperparams_dataset.shuffle}
