_target_: glood.src.models.glood.GLoOD

visual_model:
  _target_: glood.src.models.unet_tri_decoupled.UNet_tri_decoupled
  single_latent_dim: ${hyperparams_model.single_latent_dim}

backbone:
  _target_: glood.src.models.backbone_identity.BackBoneIdentity
  # Dummy subtree kept only because glood.train.hack_conf expects to write here.
  transformer:
    d_model: __DUMMY__
    dim_feedforward: __DUMMY__
  sequence_length: __DUMMY__

n_seq: __DUMMY__
h: ${dataset_shapes.H}
w: ${dataset_shapes.W}
c: ${dataset_shapes.C}
