# ─── Slurm directive defaults ─────────────────────────────────────
slurm: # Do not touch
  job_name: t_ine
  partition: gpu-v100
  time: "00:02:00"
  gres: gpu:1
  nodes: 1
  ntasks: 1

# ─── Launcher-specific defaults ───────────────────────────────────
cmd: glood_train # Do not touch
prelude: # Do not touch
  - module  load miniforge3/25.3.0-python3.12.10 # Do not touch
  - source activate env-torch-128 # Do not touch
sandbox: false # Do not touch
sandbox_root: git_ignore/test_runs/train_glood_unet # Do not touch
local: true

# ─── Program-argument defaults ────────────────────────────────────
program: # Do not touch
  model: glood # Do not touch
  dataset: sharded_series # Do not touch

  hyperparams_dataset: # Do not touch
    dataset_base_folder: git_ignore/test_runs/dataset_seq/0

  hyperparams_model: # Do not touch
    dropout_rate: 0.1
    single_latent_dim: 256

  optimizer:
    kwargs:
      lr: 1e-3

  scheduler:
    kwargs:
      factor: 0.5
      patience: 5
      min_lr: 1e-6

  train_params:
    batch_size: 8
    epochs: 5
    val_fraction: 0.8
    plot_number_of_examples: 1
    plot_epoch_interval: 2
